# Generated by Django 3.2.14 on 2022-07-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_useraccount_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
            ],
        ),
    ]
