# Generated by Django 3.2.14 on 2022-08-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_useraccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default='default', max_length=765, unique=True),
        ),
    ]
