# Generated by Django 3.2.14 on 2022-08-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_useraccount_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_staff',
        ),
    ]
