# Generated by Django 3.2.14 on 2022-08-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_useraccount_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
