# Generated by Django 3.2.14 on 2022-07-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Useraccount',
        ),
    ]
